// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetJoinTimeoutResponse_Outcome int32

const (
	SetJoinTimeoutResponse_OUTCOME_UNSPECIFIED SetJoinTimeoutResponse_Outcome = 0
	SetJoinTimeoutResponse_COUNTING            SetJoinTimeoutResponse_Outcome = 1 // state.deadline_unix_nano says when it fires
	SetJoinTimeoutResponse_PENDING             SetJoinTimeoutResponse_Outcome = 2 // not ready yet; state.timeout_nanos counts from readiness
	SetJoinTimeoutResponse_DISABLED            SetJoinTimeoutResponse_Outcome = 3
	SetJoinTimeoutResponse_CLAIMED             SetJoinTimeoutResponse_Outcome = 4 // a guest had joined, at state.first_guest_joined_unix_nano; nothing was set
	SetJoinTimeoutResponse_ENDING              SetJoinTimeoutResponse_Outcome = 5 // the timeout already fired, or the session is tearing down
)

// Enum value maps for SetJoinTimeoutResponse_Outcome.
var (
	SetJoinTimeoutResponse_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "COUNTING",
		2: "PENDING",
		3: "DISABLED",
		4: "CLAIMED",
		5: "ENDING",
	}
	SetJoinTimeoutResponse_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"COUNTING":            1,
		"PENDING":             2,
		"DISABLED":            3,
		"CLAIMED":             4,
		"ENDING":              5,
	}
)

func (x SetJoinTimeoutResponse_Outcome) Enum() *SetJoinTimeoutResponse_Outcome {
	p := new(SetJoinTimeoutResponse_Outcome)
	*p = x
	return p
}

func (x SetJoinTimeoutResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetJoinTimeoutResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (SetJoinTimeoutResponse_Outcome) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x SetJoinTimeoutResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetJoinTimeoutResponse_Outcome.Descriptor instead.
func (SetJoinTimeoutResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4, 0}
}

type Client_Kind int32

const (
	Client_GUEST Client_Kind = 0
	Client_HOST  Client_Kind = 1
)

// Enum value maps for Client_Kind.
var (
	Client_Kind_name = map[int32]string{
		0: "GUEST",
		1: "HOST",
	}
	Client_Kind_value = map[string]int32{
		"GUEST": 0,
		"HOST":  1,
	}
)

func (x Client_Kind) Enum() *Client_Kind {
	p := new(Client_Kind)
	*p = x
	return p
}

func (x Client_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Client_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (Client_Kind) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x Client_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Client_Kind.Descriptor instead.
func (Client_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8, 0}
}

type Identifier_Type int32

const (
	Identifier_HOST   Identifier_Type = 0
	Identifier_CLIENT Identifier_Type = 1
)

// Enum value maps for Identifier_Type.
var (
	Identifier_Type_name = map[int32]string{
		0: "HOST",
		1: "CLIENT",
	}
	Identifier_Type_value = map[string]int32{
		"HOST":   0,
		"CLIENT": 1,
	}
)

func (x Identifier_Type) Enum() *Identifier_Type {
	p := new(Identifier_Type)
	*p = x
	return p
}

func (x Identifier_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Identifier_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[2].Descriptor()
}

func (Identifier_Type) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[2]
}

func (x Identifier_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Identifier_Type.Descriptor instead.
func (Identifier_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9, 0}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

// StopSessionRequest asks the session to end: the command is hung up, then
// terminated, then killed, and the record reads stopped.
type StopSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// launch_id must be the launch_id of the record the caller read. A name
	// and a socket path are reused by whoever claims the name next, so they
	// do not say which run is being stopped; the launch does. The daemon
	// refuses any other value, an empty one included, so that a session that
	// ended and was replaced between the read and this call is not stopped in
	// place of the one that was inspected.
	LaunchId      string `protobuf:"bytes,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *StopSessionRequest) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

// SetJoinTimeoutRequest sets how long the session waits for its first guest,
// counted from now, or from readiness if it is not ready yet. It replaces any
// timeout already set; zero disables it.
type SetJoinTimeoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// launch_id binds the request to the launch the caller read, for the reason
	// StopSessionRequest's does.
	LaunchId      string `protobuf:"bytes,1,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	TimeoutNanos  int64  `protobuf:"varint,2,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJoinTimeoutRequest) Reset() {
	*x = SetJoinTimeoutRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJoinTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJoinTimeoutRequest) ProtoMessage() {}

func (x *SetJoinTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJoinTimeoutRequest.ProtoReflect.Descriptor instead.
func (*SetJoinTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *SetJoinTimeoutRequest) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

func (x *SetJoinTimeoutRequest) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

type SetJoinTimeoutResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Outcome       SetJoinTimeoutResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=api.SetJoinTimeoutResponse_Outcome" json:"outcome,omitempty"`
	State         *JoinState                     `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetJoinTimeoutResponse) Reset() {
	*x = SetJoinTimeoutResponse{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetJoinTimeoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetJoinTimeoutResponse) ProtoMessage() {}

func (x *SetJoinTimeoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetJoinTimeoutResponse.ProtoReflect.Descriptor instead.
func (*SetJoinTimeoutResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *SetJoinTimeoutResponse) GetOutcome() SetJoinTimeoutResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return SetJoinTimeoutResponse_OUTCOME_UNSPECIFIED
}

func (x *SetJoinTimeoutResponse) GetState() *JoinState {
	if x != nil {
		return x.State
	}
	return nil
}

// JoinState is a session's join timeout. A zero field is absent.
type JoinState struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TimeoutNanos             int64                  `protobuf:"varint,1,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`                                           // set and not claimed
	DeadlineUnixNano         int64                  `protobuf:"varint,2,opt,name=deadline_unix_nano,json=deadlineUnixNano,proto3" json:"deadline_unix_nano,omitempty"`                             // counting, or the deadline that fired
	FirstGuestJoinedUnixNano int64                  `protobuf:"varint,3,opt,name=first_guest_joined_unix_nano,json=firstGuestJoinedUnixNano,proto3" json:"first_guest_joined_unix_nano,omitempty"` // the first guest's join
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *JoinState) Reset() {
	*x = JoinState{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinState) ProtoMessage() {}

func (x *JoinState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinState.ProtoReflect.Descriptor instead.
func (*JoinState) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *JoinState) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *JoinState) GetDeadlineUnixNano() int64 {
	if x != nil {
		return x.DeadlineUnixNano
	}
	return 0
}

func (x *JoinState) GetFirstGuestJoinedUnixNano() int64 {
	if x != nil {
		return x.FirstGuestJoinedUnixNano
	}
	return 0
}

type GetSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Command          []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	ForceCommand     []string               `protobuf:"bytes,3,rep,name=force_command,json=forceCommand,proto3" json:"force_command,omitempty"`
	Host             string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	NodeAddr         string                 `protobuf:"bytes,5,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	ConnectedClients []*Client              `protobuf:"bytes,6,rep,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	AuthorizedKeys   []*AuthorizedKey       `protobuf:"bytes,7,rep,name=authorized_keys,json=authorizedKeys,proto3" json:"authorized_keys,omitempty"`
	SshUser          string                 `protobuf:"bytes,8,opt,name=ssh_user,json=sshUser,proto3" json:"ssh_user,omitempty"`                 // SSH username for client connections
	SftpDisabled     bool                   `protobuf:"varint,9,opt,name=sftp_disabled,json=sftpDisabled,proto3" json:"sftp_disabled,omitempty"` // true if SFTP is disabled (--no-sftp)
	JoinState        *JoinState             `protobuf:"bytes,10,opt,name=join_state,json=joinState,proto3" json:"join_state,omitempty"`          // the join timeout as the daemon holds it
	// launch_id is the launch this daemon speaks for, so a reader can tell the
	// run it read a record for from one that has since claimed the name. Empty
	// from a daemon that claimed no name, and from daemons before this field.
	LaunchId      string `protobuf:"bytes,11,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionResponse) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *GetSessionResponse) GetForceCommand() []string {
	if x != nil {
		return x.ForceCommand
	}
	return nil
}

func (x *GetSessionResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetSessionResponse) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

func (x *GetSessionResponse) GetConnectedClients() []*Client {
	if x != nil {
		return x.ConnectedClients
	}
	return nil
}

func (x *GetSessionResponse) GetAuthorizedKeys() []*AuthorizedKey {
	if x != nil {
		return x.AuthorizedKeys
	}
	return nil
}

func (x *GetSessionResponse) GetSshUser() string {
	if x != nil {
		return x.SshUser
	}
	return ""
}

func (x *GetSessionResponse) GetSftpDisabled() bool {
	if x != nil {
		return x.SftpDisabled
	}
	return false
}

func (x *GetSessionResponse) GetJoinState() *JoinState {
	if x != nil {
		return x.JoinState
	}
	return nil
}

func (x *GetSessionResponse) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

type AuthorizedKey struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyFingerprints []string               `protobuf:"bytes,1,rep,name=public_key_fingerprints,json=publicKeyFingerprints,proto3" json:"public_key_fingerprints,omitempty"`
	Comment               string                 `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AuthorizedKey) Reset() {
	*x = AuthorizedKey{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedKey) ProtoMessage() {}

func (x *AuthorizedKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedKey.ProtoReflect.Descriptor instead.
func (*AuthorizedKey) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizedKey) GetPublicKeyFingerprints() []string {
	if x != nil {
		return x.PublicKeyFingerprints
	}
	return nil
}

func (x *AuthorizedKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Client struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version              string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Addr                 string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	PublicKeyFingerprint string                 `protobuf:"bytes,4,opt,name=public_key_fingerprint,json=publicKeyFingerprint,proto3" json:"public_key_fingerprint,omitempty"`
	// Which door the client came in by. GUEST is zero so a reader built before
	// this field existed sees every client as a guest, which is what they were.
	Kind          Client_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=api.Client_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Client) Reset() {
	*x = Client{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *Client) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Client) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Client) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Client) GetPublicKeyFingerprint() string {
	if x != nil {
		return x.PublicKeyFingerprint
	}
	return ""
}

func (x *Client) GetKind() Client_Kind {
	if x != nil {
		return x.Kind
	}
	return Client_GUEST
}

type Identifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          Identifier_Type        `protobuf:"varint,2,opt,name=type,proto3,enum=api.Identifier_Type" json:"type,omitempty"`
	NodeAddr      string                 `protobuf:"bytes,3,opt,name=node_addr,json=nodeAddr,proto3" json:"node_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *Identifier) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identifier) GetType() Identifier_Type {
	if x != nil {
		return x.Type
	}
	return Identifier_HOST
}

func (x *Identifier) GetNodeAddr() string {
	if x != nil {
		return x.NodeAddr
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\"\x13\n" +
	"\x11GetSessionRequest\"1\n" +
	"\x12StopSessionRequest\x12\x1b\n" +
	"\tlaunch_id\x18\x01 \x01(\tR\blaunchId\"\x15\n" +
	"\x13StopSessionResponse\"Y\n" +
	"\x15SetJoinTimeoutRequest\x12\x1b\n" +
	"\tlaunch_id\x18\x01 \x01(\tR\blaunchId\x12#\n" +
	"\rtimeout_nanos\x18\x02 \x01(\x03R\ftimeoutNanos\"\xe3\x01\n" +
	"\x16SetJoinTimeoutResponse\x12=\n" +
	"\aoutcome\x18\x01 \x01(\x0e2#.api.SetJoinTimeoutResponse.OutcomeR\aoutcome\x12$\n" +
	"\x05state\x18\x02 \x01(\v2\x0e.api.JoinStateR\x05state\"d\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCOUNTING\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\f\n" +
	"\bDISABLED\x10\x03\x12\v\n" +
	"\aCLAIMED\x10\x04\x12\n" +
	"\n" +
	"\x06ENDING\x10\x05\"\x9e\x01\n" +
	"\tJoinState\x12#\n" +
	"\rtimeout_nanos\x18\x01 \x01(\x03R\ftimeoutNanos\x12,\n" +
	"\x12deadline_unix_nano\x18\x02 \x01(\x03R\x10deadlineUnixNano\x12>\n" +
	"\x1cfirst_guest_joined_unix_nano\x18\x03 \x01(\x03R\x18firstGuestJoinedUnixNano\"\xa6\x03\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12#\n" +
	"\rforce_command\x18\x03 \x03(\tR\fforceCommand\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x1b\n" +
	"\tnode_addr\x18\x05 \x01(\tR\bnodeAddr\x128\n" +
	"\x11connected_clients\x18\x06 \x03(\v2\v.api.ClientR\x10connectedClients\x12;\n" +
	"\x0fauthorized_keys\x18\a \x03(\v2\x12.api.AuthorizedKeyR\x0eauthorizedKeys\x12\x19\n" +
	"\bssh_user\x18\b \x01(\tR\asshUser\x12#\n" +
	"\rsftp_disabled\x18\t \x01(\bR\fsftpDisabled\x12-\n" +
	"\n" +
	"join_state\x18\n" +
	" \x01(\v2\x0e.api.JoinStateR\tjoinState\x12\x1b\n" +
	"\tlaunch_id\x18\v \x01(\tR\blaunchId\"a\n" +
	"\rAuthorizedKey\x126\n" +
	"\x17public_key_fingerprints\x18\x01 \x03(\tR\x15publicKeyFingerprints\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"\xbf\x01\n" +
	"\x06Client\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x124\n" +
	"\x16public_key_fingerprint\x18\x04 \x01(\tR\x14publicKeyFingerprint\x12$\n" +
	"\x04kind\x18\x05 \x01(\x0e2\x10.api.Client.KindR\x04kind\"\x1b\n" +
	"\x04Kind\x12\t\n" +
	"\x05GUEST\x10\x00\x12\b\n" +
	"\x04HOST\x10\x01\"\x81\x01\n" +
	"\n" +
	"Identifier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.api.Identifier.TypeR\x04type\x12\x1b\n" +
	"\tnode_addr\x18\x03 \x01(\tR\bnodeAddr\"\x1c\n" +
	"\x04Type\x12\b\n" +
	"\x04HOST\x10\x00\x12\n" +
	"\n" +
	"\x06CLIENT\x10\x012\xe0\x01\n" +
	"\fAdminService\x12?\n" +
	"\n" +
	"GetSession\x12\x16.api.GetSessionRequest\x1a\x17.api.GetSessionResponse\"\x00\x12B\n" +
	"\vStopSession\x12\x17.api.StopSessionRequest\x1a\x18.api.StopSessionResponse\"\x00\x12K\n" +
	"\x0eSetJoinTimeout\x12\x1a.api.SetJoinTimeoutRequest\x1a\x1b.api.SetJoinTimeoutResponse\"\x00B(Z&github.com/owenthereal/upterm/host/apib\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_goTypes = []any{
	(SetJoinTimeoutResponse_Outcome)(0), // 0: api.SetJoinTimeoutResponse.Outcome
	(Client_Kind)(0),                    // 1: api.Client.Kind
	(Identifier_Type)(0),                // 2: api.Identifier.Type
	(*GetSessionRequest)(nil),           // 3: api.GetSessionRequest
	(*StopSessionRequest)(nil),          // 4: api.StopSessionRequest
	(*StopSessionResponse)(nil),         // 5: api.StopSessionResponse
	(*SetJoinTimeoutRequest)(nil),       // 6: api.SetJoinTimeoutRequest
	(*SetJoinTimeoutResponse)(nil),      // 7: api.SetJoinTimeoutResponse
	(*JoinState)(nil),                   // 8: api.JoinState
	(*GetSessionResponse)(nil),          // 9: api.GetSessionResponse
	(*AuthorizedKey)(nil),               // 10: api.AuthorizedKey
	(*Client)(nil),                      // 11: api.Client
	(*Identifier)(nil),                  // 12: api.Identifier
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: api.SetJoinTimeoutResponse.outcome:type_name -> api.SetJoinTimeoutResponse.Outcome
	8,  // 1: api.SetJoinTimeoutResponse.state:type_name -> api.JoinState
	11, // 2: api.GetSessionResponse.connected_clients:type_name -> api.Client
	10, // 3: api.GetSessionResponse.authorized_keys:type_name -> api.AuthorizedKey
	8,  // 4: api.GetSessionResponse.join_state:type_name -> api.JoinState
	1,  // 5: api.Client.kind:type_name -> api.Client.Kind
	2,  // 6: api.Identifier.type:type_name -> api.Identifier.Type
	3,  // 7: api.AdminService.GetSession:input_type -> api.GetSessionRequest
	4,  // 8: api.AdminService.StopSession:input_type -> api.StopSessionRequest
	6,  // 9: api.AdminService.SetJoinTimeout:input_type -> api.SetJoinTimeoutRequest
	9,  // 10: api.AdminService.GetSession:output_type -> api.GetSessionResponse
	5,  // 11: api.AdminService.StopSession:output_type -> api.StopSessionResponse
	7,  // 12: api.AdminService.SetJoinTimeout:output_type -> api.SetJoinTimeoutResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
