// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: startup.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accept_Decision int32

const (
	Accept_ACCEPTED    Accept_Decision = 0
	Accept_DECLINED    Accept_Decision = 1
	Accept_INTERRUPTED Accept_Decision = 2
)

// Enum value maps for Accept_Decision.
var (
	Accept_Decision_name = map[int32]string{
		0: "ACCEPTED",
		1: "DECLINED",
		2: "INTERRUPTED",
	}
	Accept_Decision_value = map[string]int32{
		"ACCEPTED":    0,
		"DECLINED":    1,
		"INTERRUPTED": 2,
	}
)

func (x Accept_Decision) Enum() *Accept_Decision {
	p := new(Accept_Decision)
	*p = x
	return p
}

func (x Accept_Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Accept_Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_startup_proto_enumTypes[0].Descriptor()
}

func (Accept_Decision) Type() protoreflect.EnumType {
	return &file_startup_proto_enumTypes[0]
}

func (x Accept_Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Accept_Decision.Descriptor instead.
func (Accept_Decision) EnumDescriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{11, 0}
}

// Startup is one message of the exchange between `upterm host` and the
// daemon it spawned, carried over the socket the daemon inherits. The child
// sends print, read, claimed, session_created, listening, started, failed
// and hello; the parent sends line, read_failed and accept. Only read and
// session_created expect a reply.
type Startup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Startup_Print
	//	*Startup_Read
	//	*Startup_Claimed
	//	*Startup_SessionCreated
	//	*Startup_Listening
	//	*Startup_Started
	//	*Startup_Failed
	//	*Startup_Hello
	//	*Startup_Line
	//	*Startup_ReadFailed
	//	*Startup_Accept
	Msg           isStartup_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Startup) Reset() {
	*x = Startup{}
	mi := &file_startup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Startup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Startup) ProtoMessage() {}

func (x *Startup) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Startup.ProtoReflect.Descriptor instead.
func (*Startup) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{0}
}

func (x *Startup) GetMsg() isStartup_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Startup) GetPrint() *Print {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Print); ok {
			return x.Print
		}
	}
	return nil
}

func (x *Startup) GetRead() *Read {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Startup) GetClaimed() *Claimed {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Claimed); ok {
			return x.Claimed
		}
	}
	return nil
}

func (x *Startup) GetSessionCreated() *SessionCreated {
	if x != nil {
		if x, ok := x.Msg.(*Startup_SessionCreated); ok {
			return x.SessionCreated
		}
	}
	return nil
}

func (x *Startup) GetListening() *Listening {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Listening); ok {
			return x.Listening
		}
	}
	return nil
}

func (x *Startup) GetStarted() *Started {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *Startup) GetFailed() *Failed {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *Startup) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Startup) GetLine() *Line {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Line); ok {
			return x.Line
		}
	}
	return nil
}

func (x *Startup) GetReadFailed() *ReadFailed {
	if x != nil {
		if x, ok := x.Msg.(*Startup_ReadFailed); ok {
			return x.ReadFailed
		}
	}
	return nil
}

func (x *Startup) GetAccept() *Accept {
	if x != nil {
		if x, ok := x.Msg.(*Startup_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

type isStartup_Msg interface {
	isStartup_Msg()
}

type Startup_Print struct {
	Print *Print `protobuf:"bytes,1,opt,name=print,proto3,oneof"`
}

type Startup_Read struct {
	Read *Read `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type Startup_Claimed struct {
	Claimed *Claimed `protobuf:"bytes,3,opt,name=claimed,proto3,oneof"`
}

type Startup_SessionCreated struct {
	SessionCreated *SessionCreated `protobuf:"bytes,4,opt,name=session_created,json=sessionCreated,proto3,oneof"`
}

type Startup_Listening struct {
	Listening *Listening `protobuf:"bytes,5,opt,name=listening,proto3,oneof"`
}

type Startup_Started struct {
	Started *Started `protobuf:"bytes,6,opt,name=started,proto3,oneof"`
}

type Startup_Failed struct {
	Failed *Failed `protobuf:"bytes,7,opt,name=failed,proto3,oneof"`
}

type Startup_Hello struct {
	Hello *Hello `protobuf:"bytes,8,opt,name=hello,proto3,oneof"`
}

type Startup_Line struct {
	Line *Line `protobuf:"bytes,9,opt,name=line,proto3,oneof"`
}

type Startup_ReadFailed struct {
	ReadFailed *ReadFailed `protobuf:"bytes,10,opt,name=read_failed,json=readFailed,proto3,oneof"`
}

type Startup_Accept struct {
	Accept *Accept `protobuf:"bytes,11,opt,name=accept,proto3,oneof"`
}

func (*Startup_Print) isStartup_Msg() {}

func (*Startup_Read) isStartup_Msg() {}

func (*Startup_Claimed) isStartup_Msg() {}

func (*Startup_SessionCreated) isStartup_Msg() {}

func (*Startup_Listening) isStartup_Msg() {}

func (*Startup_Started) isStartup_Msg() {}

func (*Startup_Failed) isStartup_Msg() {}

func (*Startup_Hello) isStartup_Msg() {}

func (*Startup_Line) isStartup_Msg() {}

func (*Startup_ReadFailed) isStartup_Msg() {}

func (*Startup_Accept) isStartup_Msg() {}

// Print is text for the parent's stderr: a prompt's preamble, a warning.
type Print struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Print) Reset() {
	*x = Print{}
	mi := &file_startup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Print) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Print) ProtoMessage() {}

func (x *Print) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Print.ProtoReflect.Descriptor instead.
func (*Print) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{1}
}

func (x *Print) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Read asks the parent for one line from its terminal. secret means the
// line must not echo and needs a terminal; the parent answers line or
// read_failed.
type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Secret        bool                   `protobuf:"varint,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_startup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{2}
}

func (x *Read) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Read) GetSecret() bool {
	if x != nil {
		return x.Secret
	}
	return false
}

// Claimed is the daemon's first report: the name it holds and the paths that
// belong to it. Sent before the tunnel is dialled.
type Claimed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LaunchId      string                 `protobuf:"bytes,2,opt,name=launch_id,json=launchId,proto3" json:"launch_id,omitempty"`
	AdminSocket   string                 `protobuf:"bytes,3,opt,name=admin_socket,json=adminSocket,proto3" json:"admin_socket,omitempty"`
	AttachSocket  string                 `protobuf:"bytes,4,opt,name=attach_socket,json=attachSocket,proto3" json:"attach_socket,omitempty"`
	LogPath       string                 `protobuf:"bytes,5,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	Pid           int32                  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claimed) Reset() {
	*x = Claimed{}
	mi := &file_startup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claimed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claimed) ProtoMessage() {}

func (x *Claimed) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claimed.ProtoReflect.Descriptor instead.
func (*Claimed) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{3}
}

func (x *Claimed) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Claimed) GetLaunchId() string {
	if x != nil {
		return x.LaunchId
	}
	return ""
}

func (x *Claimed) GetAdminSocket() string {
	if x != nil {
		return x.AdminSocket
	}
	return ""
}

func (x *Claimed) GetAttachSocket() string {
	if x != nil {
		return x.AttachSocket
	}
	return ""
}

func (x *Claimed) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

func (x *Claimed) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// SessionCreated is gate 1: the tunnel is up and the session is registered.
// The parent shows it and answers accept.
type SessionCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *GetSessionResponse    `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreated) Reset() {
	*x = SessionCreated{}
	mi := &file_startup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreated) ProtoMessage() {}

func (x *SessionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreated.ProtoReflect.Descriptor instead.
func (*SessionCreated) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{4}
}

func (x *SessionCreated) GetSession() *GetSessionResponse {
	if x != nil {
		return x.Session
	}
	return nil
}

// Listening: the attach door is bound and these are its host keys, in
// authorized_keys form. A foreground parent attaches now.
type Listening struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttachSocket  string                 `protobuf:"bytes,1,opt,name=attach_socket,json=attachSocket,proto3" json:"attach_socket,omitempty"`
	HostKeys      []string               `protobuf:"bytes,2,rep,name=host_keys,json=hostKeys,proto3" json:"host_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listening) Reset() {
	*x = Listening{}
	mi := &file_startup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listening) ProtoMessage() {}

func (x *Listening) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listening.ProtoReflect.Descriptor instead.
func (*Listening) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{5}
}

func (x *Listening) GetAttachSocket() string {
	if x != nil {
		return x.AttachSocket
	}
	return ""
}

func (x *Listening) GetHostKeys() []string {
	if x != nil {
		return x.HostKeys
	}
	return nil
}

// Started is gate 3: the command is running and the session's record has
// been published. The parent may exit.
type Started struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// status is what the record said at the moment readiness was published --
	// ready, or disconnected if the tunnel was lost between the command
	// starting and that write, which leaves the earlier status standing. The
	// parent reports this rather than assuming ready, so that what it prints
	// and what `upterm session info` answers cannot disagree.
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Started) Reset() {
	*x = Started{}
	mi := &file_startup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{6}
}

func (x *Started) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Started) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Failed: the session did not start. name_in_use asks the parent to draw
// another name; abandoned means the parent's own answer ended it.
type Failed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	NameInUse     bool                   `protobuf:"varint,2,opt,name=name_in_use,json=nameInUse,proto3" json:"name_in_use,omitempty"`
	Abandoned     bool                   `protobuf:"varint,3,opt,name=abandoned,proto3" json:"abandoned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failed) Reset() {
	*x = Failed{}
	mi := &file_startup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failed) ProtoMessage() {}

func (x *Failed) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failed.ProtoReflect.Descriptor instead.
func (*Failed) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{7}
}

func (x *Failed) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Failed) GetNameInUse() bool {
	if x != nil {
		return x.NameInUse
	}
	return false
}

func (x *Failed) GetAbandoned() bool {
	if x != nil {
		return x.Abandoned
	}
	return false
}

// Hello carries the nonce a transport that cannot inherit a descriptor uses
// to prove the connection came from the child it spawned.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_startup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{8}
}

func (x *Hello) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// Line answers a read.
type Line struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_startup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Line.ProtoReflect.Descriptor instead.
func (*Line) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{9}
}

func (x *Line) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ReadFailed answers a read the parent could not satisfy.
type ReadFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFailed) Reset() {
	*x = ReadFailed{}
	mi := &file_startup_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFailed) ProtoMessage() {}

func (x *ReadFailed) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFailed.ProtoReflect.Descriptor instead.
func (*ReadFailed) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{10}
}

func (x *ReadFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Accept answers session_created.
type Accept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      Accept_Decision        `protobuf:"varint,1,opt,name=decision,proto3,enum=api.Accept_Decision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accept) Reset() {
	*x = Accept{}
	mi := &file_startup_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accept) ProtoMessage() {}

func (x *Accept) ProtoReflect() protoreflect.Message {
	mi := &file_startup_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accept.ProtoReflect.Descriptor instead.
func (*Accept) Descriptor() ([]byte, []int) {
	return file_startup_proto_rawDescGZIP(), []int{11}
}

func (x *Accept) GetDecision() Accept_Decision {
	if x != nil {
		return x.Decision
	}
	return Accept_ACCEPTED
}

var File_startup_proto protoreflect.FileDescriptor

const file_startup_proto_rawDesc = "" +
	"\n" +
	"\rstartup.proto\x12\x03api\x1a\tapi.proto\"\xe0\x03\n" +
	"\aStartup\x12\"\n" +
	"\x05print\x18\x01 \x01(\v2\n" +
	".api.PrintH\x00R\x05print\x12\x1f\n" +
	"\x04read\x18\x02 \x01(\v2\t.api.ReadH\x00R\x04read\x12(\n" +
	"\aclaimed\x18\x03 \x01(\v2\f.api.ClaimedH\x00R\aclaimed\x12>\n" +
	"\x0fsession_created\x18\x04 \x01(\v2\x13.api.SessionCreatedH\x00R\x0esessionCreated\x12.\n" +
	"\tlistening\x18\x05 \x01(\v2\x0e.api.ListeningH\x00R\tlistening\x12(\n" +
	"\astarted\x18\x06 \x01(\v2\f.api.StartedH\x00R\astarted\x12%\n" +
	"\x06failed\x18\a \x01(\v2\v.api.FailedH\x00R\x06failed\x12\"\n" +
	"\x05hello\x18\b \x01(\v2\n" +
	".api.HelloH\x00R\x05hello\x12\x1f\n" +
	"\x04line\x18\t \x01(\v2\t.api.LineH\x00R\x04line\x122\n" +
	"\vread_failed\x18\n" +
	" \x01(\v2\x0f.api.ReadFailedH\x00R\n" +
	"readFailed\x12%\n" +
	"\x06accept\x18\v \x01(\v2\v.api.AcceptH\x00R\x06acceptB\x05\n" +
	"\x03msg\"\x1b\n" +
	"\x05Print\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"6\n" +
	"\x04Read\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\bR\x06secret\"\xaf\x01\n" +
	"\aClaimed\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tlaunch_id\x18\x02 \x01(\tR\blaunchId\x12!\n" +
	"\fadmin_socket\x18\x03 \x01(\tR\vadminSocket\x12#\n" +
	"\rattach_socket\x18\x04 \x01(\tR\fattachSocket\x12\x19\n" +
	"\blog_path\x18\x05 \x01(\tR\alogPath\x12\x10\n" +
	"\x03pid\x18\x06 \x01(\x05R\x03pid\"C\n" +
	"\x0eSessionCreated\x121\n" +
	"\asession\x18\x01 \x01(\v2\x17.api.GetSessionResponseR\asession\"M\n" +
	"\tListening\x12#\n" +
	"\rattach_socket\x18\x01 \x01(\tR\fattachSocket\x12\x1b\n" +
	"\thost_keys\x18\x02 \x03(\tR\bhostKeys\"@\n" +
	"\aStarted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\\\n" +
	"\x06Failed\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1e\n" +
	"\vname_in_use\x18\x02 \x01(\bR\tnameInUse\x12\x1c\n" +
	"\tabandoned\x18\x03 \x01(\bR\tabandoned\"\x1d\n" +
	"\x05Hello\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"\x1a\n" +
	"\x04Line\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"$\n" +
	"\n" +
	"ReadFailed\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"s\n" +
	"\x06Accept\x120\n" +
	"\bdecision\x18\x01 \x01(\x0e2\x14.api.Accept.DecisionR\bdecision\"7\n" +
	"\bDecision\x12\f\n" +
	"\bACCEPTED\x10\x00\x12\f\n" +
	"\bDECLINED\x10\x01\x12\x0f\n" +
	"\vINTERRUPTED\x10\x02B(Z&github.com/owenthereal/upterm/host/apib\x06proto3"

var (
	file_startup_proto_rawDescOnce sync.Once
	file_startup_proto_rawDescData []byte
)

func file_startup_proto_rawDescGZIP() []byte {
	file_startup_proto_rawDescOnce.Do(func() {
		file_startup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_startup_proto_rawDesc), len(file_startup_proto_rawDesc)))
	})
	return file_startup_proto_rawDescData
}

var file_startup_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_startup_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_startup_proto_goTypes = []any{
	(Accept_Decision)(0),       // 0: api.Accept.Decision
	(*Startup)(nil),            // 1: api.Startup
	(*Print)(nil),              // 2: api.Print
	(*Read)(nil),               // 3: api.Read
	(*Claimed)(nil),            // 4: api.Claimed
	(*SessionCreated)(nil),     // 5: api.SessionCreated
	(*Listening)(nil),          // 6: api.Listening
	(*Started)(nil),            // 7: api.Started
	(*Failed)(nil),             // 8: api.Failed
	(*Hello)(nil),              // 9: api.Hello
	(*Line)(nil),               // 10: api.Line
	(*ReadFailed)(nil),         // 11: api.ReadFailed
	(*Accept)(nil),             // 12: api.Accept
	(*GetSessionResponse)(nil), // 13: api.GetSessionResponse
}
var file_startup_proto_depIdxs = []int32{
	2,  // 0: api.Startup.print:type_name -> api.Print
	3,  // 1: api.Startup.read:type_name -> api.Read
	4,  // 2: api.Startup.claimed:type_name -> api.Claimed
	5,  // 3: api.Startup.session_created:type_name -> api.SessionCreated
	6,  // 4: api.Startup.listening:type_name -> api.Listening
	7,  // 5: api.Startup.started:type_name -> api.Started
	8,  // 6: api.Startup.failed:type_name -> api.Failed
	9,  // 7: api.Startup.hello:type_name -> api.Hello
	10, // 8: api.Startup.line:type_name -> api.Line
	11, // 9: api.Startup.read_failed:type_name -> api.ReadFailed
	12, // 10: api.Startup.accept:type_name -> api.Accept
	13, // 11: api.SessionCreated.session:type_name -> api.GetSessionResponse
	0,  // 12: api.Accept.decision:type_name -> api.Accept.Decision
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_startup_proto_init() }
func file_startup_proto_init() {
	if File_startup_proto != nil {
		return
	}
	file_api_proto_init()
	file_startup_proto_msgTypes[0].OneofWrappers = []any{
		(*Startup_Print)(nil),
		(*Startup_Read)(nil),
		(*Startup_Claimed)(nil),
		(*Startup_SessionCreated)(nil),
		(*Startup_Listening)(nil),
		(*Startup_Started)(nil),
		(*Startup_Failed)(nil),
		(*Startup_Hello)(nil),
		(*Startup_Line)(nil),
		(*Startup_ReadFailed)(nil),
		(*Startup_Accept)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_startup_proto_rawDesc), len(file_startup_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_startup_proto_goTypes,
		DependencyIndexes: file_startup_proto_depIdxs,
		EnumInfos:         file_startup_proto_enumTypes,
		MessageInfos:      file_startup_proto_msgTypes,
	}.Build()
	File_startup_proto = out.File
	file_startup_proto_goTypes = nil
	file_startup_proto_depIdxs = nil
}
