version: 2
builds:
  - id: upterm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
      - "ppc64le"
      - "s390x"
    main: ./cmd/upterm
    ldflags:
      - -s -w -X github.com/owenthereal/upterm/internal/version.Version={{.Version}} -X github.com/owenthereal/upterm/internal/version.GitCommit={{.Commit}} -X github.com/owenthereal/upterm/internal/version.Date={{.CommitDate}}
  - id: uptermd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - "amd64"
      - "arm64"
      - "ppc64le"
      - "s390x"
    main: ./cmd/uptermd
    binary: uptermd
    ldflags:
      - -s -w -X github.com/owenthereal/upterm/internal/version.Version={{.Version}} -X github.com/owenthereal/upterm/internal/version.GitCommit={{.Commit}} -X github.com/owenthereal/upterm/internal/version.Date={{.CommitDate}}
archives:
  - id: upterm
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    wrap_in_directory: false
    ids:
      - upterm
    files:
      - LICENSE*
      - README*
      - etc/*
      - docs/*
  - id: uptermd
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    wrap_in_directory: false
    ids:
      - uptermd
    files:
      - LICENSE*
      - README*
homebrew_casks:
  - repository:
      owner: owenthereal
      name: homebrew-upterm
    commit_author:
      name: Owen Ou
      email: o@owenou.com
    homepage: https://upterm.dev
    description: Instant Terminal Sharing
    directory: Casks
    ids:
      - upterm
    license: "Apache 2.0"
    manpages:
      - "etc/man/man1/upterm.1"
      - "etc/man/man1/upterm-host.1"
      - "etc/man/man1/upterm-proxy.1"
      - "etc/man/man1/upterm-session.1"
      - "etc/man/man1/upterm-session-current.1"
      - "etc/man/man1/upterm-session-info.1"
      - "etc/man/man1/upterm-session-list.1"
      - "etc/man/man1/upterm-upgrade.1"
      - "etc/man/man1/upterm-version.1"
    completions:
      bash: "etc/completion/upterm.bash_completion.sh"
      zsh: "etc/completion/upterm.zsh_completion"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/upterm"]
          end
scoops:
  - repository:
      owner: owenthereal
      name: scoop-upterm
    commit_author:
      name: Owen Ou
      email: o@owenou.com
    homepage: https://upterm.dev
    description: Instant Terminal Sharing
    license: Apache-2.0
    ids:
      - upterm
dockers_v2:
  - dockerfile: Dockerfile.uptermd
    ids:
      - uptermd
    images:
      - "{{ .Env.DOCKER_REPO }}"
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
    flags:
      - "--target=pre-built-binary"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "Upterm server daemon"
      "org.opencontainers.image.url": "https://github.com/owenthereal/upterm"
      "org.opencontainers.image.source": "https://github.com/owenthereal/upterm"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": '{{ time "2006-01-02T15:04:05Z07:00" }}'
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.licenses": "Apache-2.0"
    extra_files:
      - go.mod
      - go.sum
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
release:
  prerelease: auto
  name_template: "Upterm {{.Version}}"
  mode: append
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^script:"
      - "^go.mod:"
      - "^.github:"
      - Merge branch
nfpms: #build:linux
  - license: Apache-2.0
    maintainer: Owen Ou <o@owenou.com>
    ids:
      - upterm
    homepage: https://github.com/owenthereal/upterm
    bindir: /usr/bin
    description: Instant Terminal Sharing
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - deb
      - rpm
    contents:
      - src: "./etc/man/man1/upterm*.1"
        dst: "/usr/share/man/man1"
      - src: "./etc/completion/upterm.bash_completion.sh"
        dst: "/usr/share/bash-completion/completions/upterm"
      - src: "./etc/completion/upterm.zsh_completion"
        dst: "/usr/share/zsh/site-functions/_upterm"
