// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSessionRequest struct {
	HostUser             string   `protobuf:"bytes,1,opt,name=hostUser,proto3" json:"hostUser,omitempty"`
	HostPublicKeys       [][]byte `protobuf:"bytes,2,rep,name=hostPublicKeys,proto3" json:"hostPublicKeys,omitempty"`
	ClientAuthorizedKeys [][]byte `protobuf:"bytes,3,rep,name=clientAuthorizedKeys,proto3" json:"clientAuthorizedKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionRequest) Reset()         { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()    {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionRequest.Unmarshal(m, b)
}
func (m *CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionRequest.Merge(m, src)
}
func (m *CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSessionRequest.Size(m)
}
func (m *CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionRequest proto.InternalMessageInfo

func (m *CreateSessionRequest) GetHostUser() string {
	if m != nil {
		return m.HostUser
	}
	return ""
}

func (m *CreateSessionRequest) GetHostPublicKeys() [][]byte {
	if m != nil {
		return m.HostPublicKeys
	}
	return nil
}

func (m *CreateSessionRequest) GetClientAuthorizedKeys() [][]byte {
	if m != nil {
		return m.ClientAuthorizedKeys
	}
	return nil
}

type CreateSessionResponse struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	NodeAddr             string   `protobuf:"bytes,2,opt,name=nodeAddr,proto3" json:"nodeAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSessionResponse) Reset()         { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()    {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSessionResponse.Unmarshal(m, b)
}
func (m *CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSessionResponse.Merge(m, src)
}
func (m *CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSessionResponse.Size(m)
}
func (m *CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSessionResponse proto.InternalMessageInfo

func (m *CreateSessionResponse) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateSessionResponse) GetNodeAddr() string {
	if m != nil {
		return m.NodeAddr
	}
	return ""
}

type AuthRequest struct {
	ClientVersion        string   `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	RemoteAddr           string   `protobuf:"bytes,2,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	AuthorizedKey        []byte   `protobuf:"bytes,3,opt,name=authorized_key,json=authorizedKey,proto3" json:"authorized_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetClientVersion() string {
	if m != nil {
		return m.ClientVersion
	}
	return ""
}

func (m *AuthRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *AuthRequest) GetAuthorizedKey() []byte {
	if m != nil {
		return m.AuthorizedKey
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateSessionRequest)(nil), "server.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "server.CreateSessionResponse")
	proto.RegisterType((*AuthRequest)(nil), "server.AuthRequest")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x03, 0xc5, 0x4e, 0xd3, 0x1e, 0x96, 0x0a, 0x41, 0x04, 0x43, 0x40, 0xc9, 0xc9,
	0x83, 0x3e, 0x41, 0xd1, 0x8b, 0x78, 0xd1, 0x88, 0x5e, 0x43, 0xda, 0x7c, 0xd0, 0x60, 0xcd, 0xd4,
	0x99, 0x4d, 0xa1, 0xe2, 0x33, 0xf8, 0xcc, 0xb2, 0xd9, 0xfe, 0x91, 0xe2, 0x6d, 0xe7, 0xb7, 0xb3,
	0xdf, 0xfc, 0x66, 0x29, 0x52, 0xc8, 0x1a, 0x72, 0xbd, 0x12, 0xb6, 0x6c, 0xfa, 0xbe, 0x4a, 0x7f,
	0x02, 0x9a, 0xdc, 0x09, 0x4a, 0x8b, 0x17, 0xa8, 0xd6, 0xdc, 0xe4, 0xf8, 0x6c, 0xa1, 0xd6, 0x9c,
	0xd1, 0xc9, 0x82, 0xd5, 0xbe, 0x2a, 0x24, 0x0e, 0x92, 0x20, 0x1b, 0xe4, 0xfb, 0xda, 0x5c, 0xd1,
	0xd8, 0x9d, 0x9f, 0xda, 0xd9, 0xb2, 0x9e, 0x3f, 0x62, 0xa3, 0x71, 0x2f, 0x09, 0xb3, 0x28, 0x3f,
	0xa2, 0xe6, 0x86, 0x26, 0xf3, 0x65, 0x8d, 0xc6, 0x4e, 0x5b, 0xbb, 0x60, 0xa9, 0xbf, 0x50, 0x75,
	0xdd, 0x61, 0xd7, 0xfd, 0xef, 0x5d, 0xfa, 0x4c, 0xa7, 0x47, 0x3e, 0xba, 0xe2, 0x46, 0x61, 0xce,
	0x69, 0xa0, 0x1e, 0x3d, 0xdc, 0x6f, 0x8d, 0x0e, 0xc0, 0xe9, 0x36, 0x5c, 0x61, 0x5a, 0x55, 0x12,
	0xf7, 0xbc, 0xee, 0xae, 0x4e, 0xbf, 0x69, 0xe8, 0x86, 0xec, 0x36, 0xbb, 0xa4, 0xb1, 0x9f, 0x5c,
	0xac, 0x21, 0xee, 0xf9, 0x36, 0x6d, 0xe4, 0xe9, 0x9b, 0x87, 0xe6, 0x82, 0x86, 0x82, 0x0f, 0xb6,
	0x28, 0xca, 0x43, 0x28, 0x79, 0xe4, 0x62, 0x5d, 0x4e, 0xb9, 0x77, 0x2f, 0xde, 0xb1, 0x89, 0xc3,
	0x24, 0xc8, 0xa2, 0x7c, 0x54, 0xfe, 0xdd, 0x68, 0xd6, 0xef, 0x3e, 0xfc, 0xf6, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x31, 0xc3, 0x49, 0x00, 0x80, 0x01, 0x00, 0x00,
}
