.TH "UPTERM" "1" "Mar 2020" "Upterm 0.1.2" "Upterm Manual" 
.nh
.ad l


.SH NAME
.PP
upterm\-host \- Host a terminal session


.SH SYNOPSIS
.PP
\fBupterm host [flags]\fP


.SH DESCRIPTION
.PP
Host a terminal session via a reverse SSH tunnel to the upterm server. By default, the command authenticates against the upterm server using the private keys located at \fB\fC\~/.ssh/id\_dsa\fR, \fB\fC\~/.ssh/id\_ecdsa\fR, \fB\fC\~/.ssh/id\_ed25519\fR, and \fB\fC\~/.ssh/id\_rsa\fR\&. The host can permit a list of client public keys by specifying an authorized\_keys file. By default, the input/output of the host attaches to the input/output of the client's. The host can force the execution of a command after the client joins, and attach the input/output of this command to the client's.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-authorized\-key\fP=""
    an authorized\_keys file that lists public keys that are permitted to connect.

.PP
\fB\-f\fP, \fB\-\-force\-command\fP=""
    force execution of a command and attach its input/output to client's.

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
    help for host

.PP
\fB\-i\fP, \fB\-\-private\-key\fP=[]
    private key for public key authentication against the upterm server (required).

.PP
\fB\-\-server\fP="ssh://uptermd.upterm.dev:22"
    upterm server address (required), supported protocols are shh, ws, or wss.


.SH EXAMPLE
.PP
.RS

.nf
  # Host a session by running $SHELL.
  # The client's input/output is attached to the host's.
  upterm host

  # Host a session with a custom command.
  # The client's input/output is attached to the host's.
  upterm host \-\- docker run \-\-rm \-ti ubuntu bash

  # Host a session by running 'tmux new \-t pair\-programming'.
  # The host runs 'tmux attach \-t pair\-programming' after the client joins the session.
  # The client's input/output is attached to this command's.
  upterm host \-\-force\-command 'tmux attach \-t pair\-programming' \-\- tmux new \-t pair\-programming

.fi
.RE


.SH SEE ALSO
.PP
\fBupterm(1)\fP


.SH HISTORY
.PP
16\-Mar\-2020 Auto generated by spf13/cobra
