// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIClient api client
//
// swagger:model apiClient
type APIClient struct {

	// addr
	Addr string `json:"addr,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// public key fingerprint
	PublicKeyFingerprint string `json:"public_key_fingerprint,omitempty"`
}

// Validate validates this api client
func (m *APIClient) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIClient) UnmarshalBinary(b []byte) error {
	var res APIClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
