#!/usr/bin/env bash

set -e

current_branch=$(git rev-parse --abbrev-ref HEAD)
tmp_dir=$(mktemp -d -t upterm-XXXXXXXXXX)
upterm_dir=${PWD}

pushd  $tmp_dir
helm package $upterm_dir/charts/uptermd && helm repo index .
cp $upterm_dir/README.md index.md
popd > /dev/null

git checkout gh-pages
cp $tmp_dir/* .

git add .
git commit -m "Generated website"
git push origin gh-pages

git checkout $current_branch

